security:
    encoders:
        App\Entity\User\User:
            algorithm: auto

    providers:
        db_provider:
            entity:
                class: App\Entity\User\User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            context: front
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: app.sign-in
                check_path: app.sign-in
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/upload, roles: ROLE_USER }
