security:
    encoders:
        App\Entity\User\User:
            algorithm: argon2i
            memory_cost: 1024
            time_cost: 2
            threads: 2

    providers:
        db_provider:
            entity:
                class: App\Entity\User\User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            context: front
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: app.login
                check_path: app.login.check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
